stockjournal/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StockJournal.Models;
using StockJournal.Data;
using Microsoft.AspNetCore.Authorization;

namespace StockJournal.Controllers
{
    [Authorize]
    public class StockController : Controller
    {
        private readonly IStockTransRepo _stockTransRepo;
        private readonly ICashTransRepo _cashTransRepo;
        private readonly IStockUserRepo _stockUserRepo;
        public StockController( IStockTransRepo stockTransRepo, ICashTransRepo cashTransRepo, IStockUserRepo stockUserRepo)
        {
            _stockTransRepo = stockTransRepo;
            _cashTransRepo = cashTransRepo;
            _stockUserRepo = stockUserRepo;
        }

        // GET: Stock
        public ActionResult Index(int userId)
        {
            StockViewModel stock = new StockViewModel();
            List<StockTrans> stockTransIndex = new List<StockTrans>();
            stockTransIndex = _stockTransRepo.ListAllTrans(userId);
            StockTrans stockFiller = new StockTrans();
            //stockFiller.StockUserId = userId;
            //stockTransIndex.Add(stockFiller);
            //foreach (StockTrans item in stockTransIndex)
            //{
            //    item.StockUserId = userId;
            //}
            //stock.userJournalId = userId;
            //stock.Stock.AddRange(stocks);

            return View(stockTransIndex);
        }

        // GET: Stock/Details/5
        public ActionResult Details(int id)
        {
            StockTrans stock = _stockTransRepo.GetStockTrans(id);
            StockViewModel stockview = new StockViewModel();
            stockview.userJournalId = stock.StockUserId;
            stockview.Stock = stock;
            return View(stockview);
        }

        // GET: Stock/Create
        public ActionResult Create(int userId)
        {
            StockViewModel stock = new StockViewModel();
            stock.userJournalId = userId;
            return View(stock);
            //return View();
        }

        // POST: Stock/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StockViewModel newStock, IFormCollection collection)
        {
            try
            {
                //newUser.user.Email = newUser.loginUserId;
                // TODO: Add insert logic here
                //newStock = this.User.Identity.Name;
                if (ModelState.IsValid)
                {
                    _stockTransRepo.AddStockTrans(newStock.Stock);

                    //update stock & total portfolio balances
                    _stockUserRepo.UpdateBalances("stockBal", newStock.Stock.Amount, newStock.Stock.StockUserId);
                   
                    ModelState.Clear();
                }
                var newStockId= newStock.Stock.StockUserId;
                StockViewModel newStockView = new StockViewModel();

                newStockView.userJournalId = newStockId;
                return View(newStockView);
                //return View();

                //return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Stock/Edit/5
        public ActionResult Edit(int id)
        {
            
            StockViewModel newStockView = new StockViewModel();
            StockTrans stock = _stockTransRepo.GetStockTrans(id);
            var newStockId = stock.StockUserId;
            newStockView.Stock = stock;
            newStockView.userJournalId = newStockId;

            return View(newStockView);
        }



        //public ActionResult Edit(int id, StockTrans changedStock, IFormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here
        //        _stockTransRepo.UpdateStock(changedStock);
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
        // POST: Stock/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, StockViewModel changedStock, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                if (ModelState.IsValid)
                {
                    _stockTransRepo.UpdateStock(changedStock.Stock);
                    // return RedirectToAction(nameof(Index));
                    //ModelState.Clear();

                }

                StockViewModel newStockView = new StockViewModel();
                newStockView.userJournalId = changedStock.Stock.StockUserId;
                //newStockView.Stock = changedStock;
                return View(newStockView);
            }
            catch
            {
                return View();
            }
        }

        // GET: Stock/Delete/5
        public ActionResult Delete(int id)
        {
            StockTrans stock = _stockTransRepo.GetStockTrans(id);
            StockViewModel stockview = new StockViewModel();
            stockview.userJournalId = stock.StockUserId;
            stockview.Stock = stock;
            return View(stockview);
        }

        // POST: Stock/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                StockTrans stock = _stockTransRepo.GetStockTrans(id);
                StockViewModel stockview = new StockViewModel();
                stockview.userJournalId = stock.StockUserId;
                //stockview.Stock = stock;
                if (ModelState.IsValid)
                {
                    
                    _stockTransRepo.DeleteStock(_stockTransRepo.GetStockTrans(id));
                    ModelState.Clear();
                }
                
                return View(stockview);

                //return RedirectToAction(nameof(Index), new { id = stockview.userJournalId });
            }
            catch
            {
                return View();
            }
        }
    }
}

stockjournal/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StockJournal.Models;
using StockJournal.Data;
using Microsoft.AspNetCore.Authorization;

namespace StockJournal.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IStockUserRepo _StockUserRepo;
        private readonly IStockTransRepo _StockTransRepo;
        private readonly ICashTransRepo _CashTransRepo;


        public UserController(IStockUserRepo userRepo, IStockTransRepo stockTransRepo, ICashTransRepo cashTransRepo)
        {
            _StockUserRepo = userRepo;
            _StockTransRepo = stockTransRepo;
            _CashTransRepo = cashTransRepo;
           
        }

        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: User/Create
        public ActionResult Create()
        {
            StockUserViewModel stockUser = new StockUserViewModel();
            stockUser.loginUserId= this.User.Identity.Name;
            stockUser.userTransId = 0;
            // stockUser.user.Id = 0;
            //lookup email--if exists, populate form with data
            StockUser userFound = _StockUserRepo.GetUserInfo(stockUser.loginUserId);

            if(userFound != null)
            {
                //populate view model with stockuser data
                stockUser.user.Id = userFound.Id;
                stockUser.user.FName = userFound.FName;
                stockUser.user.LName = userFound.LName;
                stockUser.user.TotCash = userFound.TotCash;
                stockUser.user.TotEquity = userFound.TotEquity;
                stockUser.user.TotPortfolio = userFound.TotPortfolio;
            }

            return View(stockUser);
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StockUserViewModel newUser,IFormCollection collection)
        {
            try
            {
                //newUser.user.Email = newUser.loginUserId;
                // TODO: Add insert logic here
                newUser.loginUserId = this.User.Identity.Name;              
                _StockUserRepo.AddUser( newUser.user);
                newUser.userTransId = newUser.user.Id;

                return View(newUser);

                //return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: User/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

stockjournal/Views/User/Create.cshtml
@model StockJournal.Models.StockUserViewModel

@{
    ViewData["Title"] = "Create";
    ViewBag.userId = Model.userTransId;
    //ViewBag.userId = 7;
}

<h2>MY PROFILE</h2>


<hr />
<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="user.Id"/>          
            <div class="form-group">
                <label asp-for="user.FName" class="control-label"></label>
                <input asp-for="user.FName" class="form-control" disabled />
                <span asp-validation-for="user.FName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="user.LName" class="control-label"></label>
                <input asp-for="user.LName" class="form-control" disabled />
                <span asp-validation-for="user.LName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="user.Email" class="control-label"></label>
                <input asp-for="user.Email" value ="@Model.loginUserId" class="form-control" disabled />
                <span asp-validation-for="user.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="user.TotCash" class="control-label" ></label>
                <input asp-for="user.TotCash" class="form-control" id="idCash" disabled/>
                <span asp-validation-for="user.TotCash" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="user.TotEquity" class="control-label"></label>
                <input asp-for="user.TotEquity" class="form-control" disabled/>
                <span asp-validation-for="user.TotEquity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="user.TotPortfolio" class="control-label"></label>
                <input asp-for="user.TotPortfolio" class="form-control" disabled />
                <span asp-validation-for="user.TotPortfolio" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <input type="submit" value="Save Profile" class="btn btn-default" />
            </div>*@
        </form>
    </div>
</div>

<div class="col-md-offset-4 col-md-4">
   

    @Html.ActionLink("Manage Transactions", "Index", "Stock", new { userId = Model.user.Id }, new { @class = "btn btn-primary btn-large" })
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>
    (function () {
        var cash = document.getElementById("idCash");
        var equity = document.getElementById("idEquity");


        window.onload = function () {
            if (cash.innerText == "") {
                cash.disabled = true;

            }
        }

    })();
</script>

}